# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy

name: Build and deploy ASP.Net Core app to Azure Web App - gainscoai-api

on:
push:
branches:
- main
workflow_dispatch:

jobs:
build:
runs-on: ubuntu-latest

permissions:
contents: read

steps:
- name: Checkout source
uses: actions/checkout@v4

- name: Setup .NET 8
uses: actions/setup-dotnet@v4
with:
dotnet-version: '8.0.x'

- name: Restore NuGet packages
run: dotnet restore GainscoAI/GainscoAI.sln

- name: Build solution
run: dotnet build GainscoAI/GainscoAI.sln --configuration Release --no-restore

- name: Publish API
run: dotnet publish GainscoAI/GainscoAI.Api/GainscoAI.Api.csproj --configuration Release --no-build --output ${{ env.DOTNET_ROOT }}/myapp

- name: Upload deployment artifact
uses: actions/upload-artifact@v4
with:
name: .net-app
path: ${{ env.DOTNET_ROOT }}/myapp

deploy:
runs-on: ubuntu-latest
needs: build

permissions:
id-token: write
contents: read

steps:
- name: Download deployment artifact
uses: actions/download-artifact@v4
with:
name: .net-app

- name: Login to Azure
uses: azure/login@v2
with:
client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_37F038DBC5774EF39836160387017145 }}
tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_341F84CA1A3A4B23AB4849264E51BB6E }}
subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9C055C4132C1419F8411655F53DEBA96 }}

- name: Deploy to Azure Web App
id: deploy-to-webapp
uses: azure/webapps-deploy@v3
with:
app-name: gainscoai-api
slot-name: Production
package: .
